version: "3.8"
services:
  redis:
    image: redis:7-alpine
    container_name: redis-${APP_PREFIX}
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - web
  backend:
    container_name: ${APP_PREFIX}-backend
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    volumes:
      - ./backend/public:/app/public
    depends_on:
      - redis
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_PREFIX}-backend.rule=Host(`${BACKEND_HOST}`)"
      - "traefik.http.routers.${APP_PREFIX}-backend.entrypoints=websecure"
      - "traefik.http.routers.${APP_PREFIX}-backend.tls.certresolver=le"
      - "traefik.http.services.${APP_PREFIX}-backend.loadbalancer.server.port=${BACKEND_PORT}"
  apioficial:
    container_name: ${APP_PREFIX}-apioficial
    build: ./api_oficial
    restart: always
    env_file:
      - ./api_oficial/.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_PREFIX}-apioficial.rule=Host(`${APIOFICIAL_HOST}`)"
      - "traefik.http.routers.${APP_PREFIX}-apioficial.entrypoints=websecure"
      - "traefik.http.routers.${APP_PREFIX}-apioficial.tls.certresolver=le"
      - "traefik.http.services.${APP_PREFIX}-apioficial.loadbalancer.server.port=${APIOFICIAL_PORT}"
  frontend:
    container_name: ${APP_PREFIX}-frontend
    build: ./frontend
    restart: always
    env_file:
      - ./frontend/.env
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_PREFIX}-frontend.rule=Host(`${FRONTEND_HOST}`)"
      - "traefik.http.routers.${APP_PREFIX}-frontend.entrypoints=websecure"
      - "traefik.http.routers.${APP_PREFIX}-frontend.tls.certresolver=le"
      - "traefik.http.services.${APP_PREFIX}-frontend.loadbalancer.server.port=${FRONTEND_PORT}"
networks:
  web:
    external: true
volumes:
  redis_data:
    name: "redis_${APP_PREFIX}_data"
